### ISSUE TITLE
Pressing the enter key can throw this error

### ISSUE THREAD

**Issue by palewire** [datadesk/bing-geocodify#6]
![screenshot from 2017-04-06 09-35-55](https://cloud.githubusercontent.com/assets/9993/24765694/a220d372-1aad-11e7-9f05-d826388e4381.png)

**Comment by palewire** [comment]
Could it be the difference between KeyDown and KeyUp? I only see KeyUp handled in the code.

**Comment by joemfox** [comment]
I think I fixed this — added a message to say when there are no results and also it is checking to see if there are any results before it allows a result to be selected. Pretty sure this is closed.
