### ISSUE TITLE
Since Bing is a bit of slowpoke returning results, it might help calm users to have some kind of spinning wheel or processing symbol

### ISSUE THREAD

**Issue by palewire** [datadesk/bing-geocodify#7]

**Comment by jschleuss** [comment]
If we can figure out the bug, this works. Otherwise we'll move to have a "search" button that fires only one API request and provides results. If there is only one result, then the no results are displayed and the one result is passed on.

**Comment by joemfox** [comment]
There is now a "searching" message that shows up when a request is in progress. Not perfect, but it's good enough to close this.
